RoFISim: Rename targets

diff --git a/simulator/Makefile b/simulator/Makefile
--- a/simulator/Makefile
+++ b/simulator/Makefile
@@ -1,15 +1,15 @@
 default: build-all
 
 GAZEBO ?= gazebo
-GAZEBO_ARGS ?= --verbose
+GZ_ARGS ?= --verbose
 WORLD ?=
 
-EXAMPLE ?=
+NAME ?=
 ARGS ?=
 
-SUBFOLDERS = demo examples hal plugins tools worlds
+SUBFOLDERS = demos examples hal plugins tools worlds
 
-.PHONY: build-all clean run tests-roficom format-all example help worlds-all ${SUBFOLDERS}
+.PHONY: build-all clean run tests-roficom format-all demo example world-creator help ${SUBFOLDERS}
 
 build:
 	mkdir -p build
@@ -19,10 +19,6 @@ build-all: build
 	cd build && make -j8
 	@echo "\nBuild completed\n\n"
 
-worlds-all: build
-	cd build && make worlds-all -j8
-	@echo "\nBuild $@ completed\n\n"
-
 ${SUBFOLDERS} : build
 	cd build/$@ && make -j8
 	@echo "\nBuild $@ completed\n\n"
@@ -30,8 +26,8 @@ ${SUBFOLDERS} : build
 clean:
 	rm -rf build
 
-run: plugins worlds-all
-	./setGazeboVariables.sh ${GAZEBO} ${GAZEBO_ARGS} ${WORLD}
+run: plugins worlds
+	./setGazeboVariables.sh ${GAZEBO} ${GZ_ARGS} ${WORLD}
 
 tests-roficom: plugins
 	./build/plugins/roficom/tests/tests_roficom
@@ -39,14 +35,14 @@ tests-roficom: plugins
 format-all:
 	find ./ ! \( -path "./build/*" \) -a \( -type f -iname *.hpp -o -type f -iname *.cpp \) | xargs clang-format --style=file -i
 
-example: build
-ifndef EXAMPLE
-	$(error EXAMPLE is not set. Call 'make help' for more info)
+demo example: build
+ifndef NAME
+	$(error NAME is not set. Call 'make help' for more info)
 endif
-	cd build && make -j8 ${EXAMPLE}
-	@test -f ./build/examples/${EXAMPLE}/${EXAMPLE} || \
-		( echo "\nERROR: No example '${EXAMPLE}' found\nCall 'make help' for more info\n" ; exit 1 )
-	./build/examples/${EXAMPLE}/${EXAMPLE} ${ARGS}
+	cd build && make -j8 ${NAME}
+	@test -f ./build/$@s/${NAME}/${NAME} || \
+		( echo "\nERROR: No $@ '${NAME}' found\nCall 'make help' for more info\n" ; exit 1 )
+	./build/$@s/${NAME}/${NAME} ${ARGS}
 
 world-creator: build
 	cd build && make worldCreator -j8
@@ -57,21 +53,22 @@ help:
 	@echo "Available targets:"
 	@echo "\n\t[build-all]"
 	@echo "\t\tBuilds the project."
-	@echo "\n\t[${SUBFOLDERS}]"
+	@echo "\n\t(${SUBFOLDERS})"
 	@echo "\t\tBuilds the given folder in project."
+	@echo "\t\t(Target 'worlds' creates all worlds in the project.)"
 	@echo "\n\tclean"
 	@echo "\t\tRemoves the build directory."
-	@echo "\n\tworlds-all"
-	@echo "\t\tCreates all worlds in the project."
-	@echo "\n\trun [GAZEBO=<gazebo_program>] [GAZEBO_ARGS=<gazebo_args>] [WORLD=<path_to_world>]"
+	@echo "\n\trun [GAZEBO=<gazebo_program>] [GZ_ARGS=<gazebo_args>] [WORLD=<world_file>]"
 	@echo "\t\tRuns gazebo, gazebo_args default to '--verbose'."
 	@echo "\n\ttests-roficom"
 	@echo "\t\tRuns tests for roficom."
 	@echo "\n\tformat-all"
 	@echo "\t\tFormats all '.hpp' and '.cpp' files."
-	@echo "\n\texample EXAMPLE=<example_name> [ARGS=<example_args>]"
+	@echo "\n\tdemo NAME=<demo_name> [ARGS=<demo_args>]"
+	@echo "\t\tRuns the RoFISim client for the demo."
+	@echo "\n\texample NAME=<example_name> [ARGS=<example_args>]"
 	@echo "\t\tRuns the RoFISim client for the example."
-	@echo "\n\tworld-creator ARGS=\"[-i <input_file>] [-o <output_file>] [-w <world_file>]\""
+	@echo "\n\tworld-creator ARGS=\"[-i <input_file>] [-o <output_file>] [-w <empty_world_file>]\""
 	@echo "\t\tRuns the World creator tool. (Note the quotation marks around ARGS value.)"
 	@echo "\t\tIf not set, uses the standard input/output."
 	@echo "\n\thelp"
